#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 23, 2020 10:18:35 AM JST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1191x750+1762+153
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3290 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can45 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 316 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 353 
    vTcl:DefineAlias "$top.can45" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 315 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 354 
    vTcl:DefineAlias "$top.can46" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can47 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 313 -insertbackground black -relief ridge \
        -selectbackground blue -selectforeground white -width 373 
    vTcl:DefineAlias "$top.can47" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu48 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$top.tBu48" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu49 \
        -takefocus {} -text Tbutton 
    vTcl:DefineAlias "$top.tBu49" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can45 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.013 -width 0 -relwidth 0.296 \
        -height 0 -relheight 0.421 -anchor nw -bordermode ignore 
    place $top.can46 \
        -in $top -x 0 -relx 0.344 -y 0 -rely 0.013 -width 0 -relwidth 0.296 \
        -height 0 -relheight 0.42 -anchor nw -bordermode ignore 
    place $top.can47 \
        -in $top -x 0 -relx 0.672 -y 0 -rely 0.013 -width 0 -relwidth 0.313 \
        -height 0 -relheight 0.417 -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 0 -relx 0.411 -y 0 -rely 0.52 -width 206 -relwidth 0 \
        -height 55 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 0 -relx 0.411 -y 0 -rely 0.627 -width 206 -relwidth 0 \
        -height 55 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

